{
"SendMessage":4,
"MyMessage":
"WELCOME AND ENJOY
 ZENITH VPN 
- GTM NO LOAD
- STS NO LOAD
- PROMONET ( NO BLOCK ) 
GIGA STORIES PWEDE NA SA TIKTOK BASED PROMO
PLEASE NEED KO NG FEEDBACK KUNG ANONG ANDROID VERSION CP NYO. SA 3 LINES BOTTON PLEASE FEEDBACK KAYO TAP NYO LANG YUNG MESSENGER ICON ✓ SALAMAT"
}
