{
"SendMessage":13,
"MyMessage":"\n ZENITH VPN
\n\n- GTM NO LOAD ( IP HUNT )
\n- STS NO LOAD ( SLOW DNS )
\n- GTM NO LOAD ( SLOW DNS )
\n- PROMONET ( NO BLOCKING )
\n- PISO WIFI ( DNS )
\n\n-INGATAN LANG. \n ANG SERVER PARA MAG TAGAL
\n\nBy: ALVIN DCTV "}
