{
"SendMessage":16,
"MyMessage":"\n ZENITH VPN
\n\n- GTM NO LOAD ( IP HUNT )
\n- STS NO LOAD ( SLOW DNS )
\n- STS NO LOAD ( CLOUD FRONT )
\n- GTM NO LOAD ( SLOW DNS )
\n- PROMONET ( NO BLOCKING )
\n- PISO WIFI ( DNS )
\n- ADDED PH SERVERS
\n- NEW VERSION NG APP TAYO KASI FIX NA ANG SA CLOUD FRONT SET UP
\nBy: ALVIN DCTV "}
